### ISSUE TITLE
overlaycolor

### ISSUE THREAD

**Issue by OvenCroc** [centerzx/ShapeBlurView#5]
大佬 设置了blur_overlay_color 就么有毛玻璃效果了, 我其实只是想给毛玻璃加点颜色, 现在库默认是透明, 想加个其他的颜色, 然后有毛玻璃效果, 有相应的属性么

**Comment by centerzx** [comment]
抱歉哈，我看看，可能又改出Bug了，尬脸~

**Comment by centerzx** [comment]
问题是这样的，要用带透明度的颜色就行。有的需求颜色值重，有的颜色值浅，所以就自己控制透明度就好

**Comment by OvenCroc** [comment]
大佬牛逼~~~ [破音]
