### ISSUE TITLE
毛玻璃效果只在普通view上有用，在videoview这些surfaceview上无效果

### ISSUE THREAD

**Issue by SchafferWang0818** [centerzx/ShapeBlurView#6]
毛玻璃效果只在普通view上有用，在videoview这些surfaceview上无效果

**Comment by centerzx** [comment]
这个还没试过，空了看看

**Comment by centerzx** [comment]
暂时不支持：
SurfaceView, TextureView, VideoView, MapFragment, GLSurfaceView, etc
BlurView currently doesn't support blurring of these targets, because they work only with hardware-accelerated Canvas, and BlurView relies on a software Canvas to make a snapshot of Views to blur.
